import { HackingTool, EncryptionMode } from './types';

export const MODES_METADATA: Record<EncryptionMode, { name: string; desc: string; strength: number }> = {
  [EncryptionMode.AES_GCM]: { name: 'AES-256-GCM', desc: 'Galois/Counter Mode. High performance, authenticated encryption.', strength: 95 },
  [EncryptionMode.AES_CCM]: { name: 'AES-256-CCM', desc: 'Counter with CBC-MAC. Standard for WiFi security (WPA2).', strength: 90 },
  [EncryptionMode.CHACHA20_POLY1305]: { name: 'ChaCha20-Poly1305', desc: 'Modern stream cipher. Faster than AES on mobile hardware.', strength: 96 },
  [EncryptionMode.AES_GCM_SIV]: { name: 'AES-GCM-SIV', desc: 'Nonce-misuse resistant authenticated encryption.', strength: 98 },
  [EncryptionMode.AES_CTR_HMAC_SHA512]: { name: 'AES-CTR + HMAC-SHA512', desc: 'Traditional Encrypt-then-MAC construction.', strength: 92 },
  [EncryptionMode.XCHACHA20_POLY1305]: { name: 'XChaCha20-Poly1305', desc: 'ChaCha20 with extended nonce for safer random nonces.', strength: 99 },
  [EncryptionMode.AES_CBC_HMAC_SHA256]: { name: 'AES-CBC + HMAC-SHA256', desc: 'Legacy authenticated encryption (TLS 1.2 style).', strength: 85 },
  [EncryptionMode.AES_OCB]: { name: 'AES-OCB', desc: 'Offset Codebook Mode. Parallelizable and efficient.', strength: 94 },
  [EncryptionMode.UNIFIED_PRISM]: { name: 'UNIFIED-PRISM-CORE', desc: 'Proprietary multi-layer cryptographic orchestration.', strength: 100 },
};

export const TOOLS_DATABASE: HackingTool[] = [
  // --- RECON & INFORMATION GATHERING (OSINT/DNS/NETWORK) ---
  { name: "Nmap", category: "Recon", description: "Network mapper and security scanner.", usage: "nmap -sV -sC target", icon: "fa-radar", difficulty: "Beginner" },
  { name: "Masscan", category: "Recon", description: "Internet-wide port scanner, extremely fast.", usage: "masscan -p80 --rate 1000 0.0.0.0/0", icon: "fa-gauge-high", difficulty: "Intermediate" },
  { name: "ZMap", category: "Recon", description: "Open source network scanner for internet-wide surveys.", usage: "zmap -p 80", icon: "fa-globe", difficulty: "Intermediate" },
  { name: "Amass", category: "Recon", description: "In-depth attack surface mapping and asset discovery.", usage: "amass enum -d domain.com", icon: "fa-map", difficulty: "Intermediate" },
  { name: "Subfinder", category: "Recon", description: "Fast passive subdomain discovery tool.", usage: "subfinder -d target.com", icon: "fa-magnifying-glass", difficulty: "Beginner" },
  { name: "Assetfinder", category: "Recon", description: "Find subdomains potentially related to a given domain.", usage: "assetfinder target.com", icon: "fa-search", difficulty: "Beginner" },
  { name: "Chaos", category: "Recon", description: "Go client to interact with Chaos DNS project.", usage: "chaos -d target.com", icon: "fa-hurricane", difficulty: "Intermediate" },
  { name: "Findomain", category: "Recon", description: "The fastest subdomain enumeration tool.", usage: "findomain -t target.com", icon: "fa-bolt", difficulty: "Beginner" },
  { name: "DNSRecon", category: "Recon", description: "DNS enumeration and zone transfer script.", usage: "dnsrecon -d target.com", icon: "fa-server", difficulty: "Intermediate" },
  { name: "Dnsenum", category: "Recon", description: "Multithreaded script to enumerate DNS and discover non-contiguous ip blocks.", usage: "dnsenum target.com", icon: "fa-list-ol", difficulty: "Intermediate" },
  { name: "TheHarvester", category: "Recon", description: "E-mails, subdomains and names Harvester.", usage: "theHarvester -d target.com -b google", icon: "fa-crop", difficulty: "Beginner" },
  { name: "Sherlock", category: "Recon", description: "Hunt down social media accounts by username.", usage: "sherlock username", icon: "fa-user-secret", difficulty: "Beginner" },
  { name: "Maltego", category: "Recon", description: "Open source intelligence and forensics application.", usage: "maltego", icon: "fa-diagram-project", difficulty: "Advanced" },
  { name: "WhatWeb", category: "Recon", description: "Identify website technologies.", usage: "whatweb target.com", icon: "fa-question", difficulty: "Beginner" },
  { name: "Wappalyzer", category: "Recon", description: "Browser extension/CLI to identify web technologies.", usage: "wappalyzer target.com", icon: "fa-microchip", difficulty: "Beginner" },
  { name: "BuiltWith", category: "Recon", description: "Find out what a website is built with.", usage: "builtwith target.com", icon: "fa-gears", difficulty: "Beginner" },
  { name: "Recon-ng", category: "Recon", description: "Full-featured Web Reconnaissance Framework.", usage: "recon-ng", icon: "fa-satellite", difficulty: "Intermediate" },
  { name: "SpiderFoot", category: "Recon", description: "OSINT automation tool.", usage: "spiderfoot -l 127.0.0.1:5001", icon: "fa-spider", difficulty: "Intermediate" },
  { name: "Httpx", category: "Recon", description: "Multipurpose HTTP toolkit.", usage: "httpx -l urls.txt", icon: "fa-globe", difficulty: "Beginner" },
  { name: "Gau", category: "Recon", description: "Getallurls - Fetch known URLs from AlienVault, Wayback, and Common Crawl.", usage: "gau target.com", icon: "fa-link", difficulty: "Beginner" },
  { name: "Waybackurls", category: "Recon", description: "Fetch URLs that the Wayback Machine knows about for a domain.", usage: "waybackurls target.com", icon: "fa-clock-rotate-left", difficulty: "Beginner" },
  { name: "Katana", category: "Recon", description: "A next-generation crawling and spidering framework.", usage: "katana -u target.com", icon: "fa-sword", difficulty: "Intermediate" },
  { name: "Feroxbuster", category: "Recon", description: "A simple, fast, recursive content discovery tool.", usage: "feroxbuster -u http://target", icon: "fa-ghost", difficulty: "Beginner" },
  { name: "Dirb", category: "Recon", description: "Web Content Scanner.", usage: "dirb http://target", icon: "fa-folder-open", difficulty: "Beginner" },
  { name: "Dirbuster", category: "Recon", description: "Multi-threaded content discovery tool.", usage: "dirbuster", icon: "fa-folder-tree", difficulty: "Beginner" },
  { name: "Gobuster", category: "Recon", description: "Tool used to brute-force URI/DNS.", usage: "gobuster dir -u http://target -w list.txt", icon: "fa-door-open", difficulty: "Beginner" },
  { name: "Ffuf", category: "Recon", description: "Fast web fuzzer written in Go.", usage: "ffuf -u http://target/FUZZ -w list.txt", icon: "fa-bolt-lightning", difficulty: "Intermediate" },
  { name: "Arjun", category: "Recon", description: "HTTP parameter discovery suite.", usage: "arjun -u http://target", icon: "fa-filter", difficulty: "Intermediate" },

  // --- VULNERABILITY ANALYSIS & SCANNING ---
  { name: "Nikto", category: "Web Scan", description: "Web server scanner which performs comprehensive tests.", usage: "nikto -h target", icon: "fa-circle-exclamation", difficulty: "Beginner" },
  { name: "Nuclei", category: "Web Scan", description: "Template-based vulnerability scanner.", usage: "nuclei -u target", icon: "fa-atom", difficulty: "Intermediate" },
  { name: "Wpscan", category: "Web Scan", description: "WordPress vulnerability scanner.", usage: "wpscan --url http://site", icon: "fa-wordpress", difficulty: "Beginner" },
  { name: "Joomscan", category: "Web Scan", description: "Joomla vulnerability scanner.", usage: "joomscan -u http://site", icon: "fa-j", difficulty: "Beginner" },
  { name: "Droopescan", category: "Web Scan", description: "Drupal/Silverstripe/WordPress scanner.", usage: "droopescan scan drupal -u http://site", icon: "fa-droplet", difficulty: "Beginner" },
  { name: "OWASP ZAP", category: "Web Scan", description: "Open source web application security scanner.", usage: "zaproxy", icon: "fa-shield-halved", difficulty: "Beginner" },
  { name: "Burp Suite", category: "Web Scan", description: "Web application security testing platform.", usage: "burpsuite", icon: "fa-spider", difficulty: "Intermediate" },
  { name: "OpenVAS", category: "Vuln Scan", description: "Full-featured vulnerability scanner and manager.", usage: "openvas", icon: "fa-shield-virus", difficulty: "Advanced" },
  { name: "Nessus", category: "Vuln Scan", description: "Proprietary vulnerability scanner.", usage: "nessus", icon: "fa-vial", difficulty: "Intermediate" },
  { name: "Gvm", category: "Vuln Scan", description: "Greenbone Vulnerability Manager.", usage: "gvm-start", icon: "fa-server", difficulty: "Advanced" },
  { name: "Sqlmap", category: "Exploitation", description: "Automatic SQL injection and database takeover tool.", usage: "sqlmap -u target", icon: "fa-database", difficulty: "Intermediate" },
  { name: "Tplmap", category: "Exploitation", description: "SSTI and code injection tool.", usage: "tplmap -u target", icon: "fa-code", difficulty: "Advanced" },
  { name: "Xsser", category: "Exploitation", description: "Automatic Cross Site Scripter analyzer.", usage: "xsser -u target", icon: "fa-font-awesome", difficulty: "Intermediate" },
  { name: "Dalfox", category: "Exploitation", description: "Parameter analysis and XSS scanning tool.", usage: "dalfox url target", icon: "fa-eye", difficulty: "Intermediate" },

  // --- PASSWORD ATTACKS & CRACKING ---
  { name: "John the Ripper", category: "Passwords", description: "Fast password cracker.", usage: "john hash.txt", icon: "fa-hand-scissors", difficulty: "Intermediate" },
  { name: "Hashcat", category: "Passwords", description: "World's fastest system-independent password cracker.", usage: "hashcat -m 0 hash.txt", icon: "fa-fire", difficulty: "Advanced" },
  { name: "Hydra", category: "Passwords", description: "Network login cracker.", usage: "hydra -l user -P list.txt target ssh", icon: "fa-dragon", difficulty: "Intermediate" },
  { name: "Medusa", category: "Passwords", description: "Parallel network login brute-forcer.", usage: "medusa -h target -U users.txt -P pass.txt -M ssh", icon: "fa-snake", difficulty: "Intermediate" },
  { name: "Ncrack", category: "Passwords", description: "High-speed network authentication cracking tool.", usage: "ncrack target", icon: "fa-bolt", difficulty: "Intermediate" },
  { name: "CeWL", category: "Passwords", description: "Custom Word List Generator.", usage: "cewl -w out.txt http://target", icon: "fa-file-lines", difficulty: "Beginner" },
  { name: "Crunch", category: "Passwords", description: "Wordlist generator using custom character sets.", usage: "crunch 4 6 abc123", icon: "fa-keyboard", difficulty: "Beginner" },
  { name: "Cupp", category: "Passwords", description: "Common User Passwords Profiler.", usage: "python cupp.py -i", icon: "fa-user-gear", difficulty: "Beginner" },
  { name: "Mimikatz", category: "Post-Ex", description: "Windows credentials extractor from memory.", usage: "mimikatz", icon: "fa-cat", difficulty: "Advanced" },
  { name: "Lazagne", category: "Post-Ex", description: "Retrieve passwords stored on a local computer.", usage: "lazagne.exe all", icon: "fa-key", difficulty: "Beginner" },
  { name: "Rubeus", category: "Post-Ex", description: "Kerberos interaction and abuse.", usage: "Rubeus.exe triage", icon: "fa-shield-dog", difficulty: "Advanced" },
  { name: "SharpHound", category: "Post-Ex", description: "Ingestor for BloodHound.", usage: "SharpHound.exe -c All", icon: "fa-skull", difficulty: "Intermediate" },
  { name: "Evil-WinRM", category: "Exploitation", description: "WinRM shell for pentesting Windows.", usage: "evil-winrm -i target -u user -p pass", icon: "fa-windows", difficulty: "Intermediate" },

  // --- EXPLOITATION FRAMEWORKS ---
  { name: "Metasploit", category: "Exploitation", description: "The most used penetration testing framework.", usage: "msfconsole", icon: "fa-rocket", difficulty: "Intermediate" },
  { name: "BeEF", category: "Exploitation", description: "The Browser Exploitation Framework.", usage: "beef-xss", icon: "fa-cow", difficulty: "Intermediate" },
  { name: "Searchsploit", category: "Exploitation", description: "Command line search tool for Exploit-DB.", usage: "searchsploit apache", icon: "fa-magnifying-glass", difficulty: "Beginner" },
  { name: "Social Engineering Toolkit", category: "Exploitation", description: "Toolkit for social engineering attacks.", usage: "setoolkit", icon: "fa-users", difficulty: "Intermediate" },
  { name: "Empire", category: "Exploitation", description: "PowerShell and Python post-exploitation framework.", usage: "powershell-empire", icon: "fa-crown", difficulty: "Advanced" },
  { name: "Covenant", category: "Exploitation", description: "Collaborative .NET C2 framework.", usage: "dotnet Covenant.dll", icon: "fa-handshake", difficulty: "Advanced" },
  { name: "Sliver", category: "Exploitation", description: "Cross-platform implant framework.", usage: "sliver-server", icon: "fa-ghost", difficulty: "Advanced" },
  { name: "Havoc", category: "Exploitation", description: "Modern and malleable C2 framework.", usage: "havoc", icon: "fa-mask", difficulty: "Advanced" },
  { name: "Armitage", category: "Exploitation", description: "GUI for Metasploit.", usage: "armitage", icon: "fa-crosshairs", difficulty: "Intermediate" },
  { name: "Routersploit", category: "Exploitation", description: "Exploitation framework for embedded devices.", usage: "rsf", icon: "fa-wifi", difficulty: "Intermediate" },

  // --- WIRELESS ATTACKS ---
  { name: "Aircrack-ng", category: "Wireless", description: "Network software suite consisting of a detector, packet sniffer.", usage: "aircrack-ng file.cap", icon: "fa-wifi", difficulty: "Intermediate" },
  { name: "Kismet", category: "Wireless", description: "Wireless network detector and sniffer.", usage: "kismet", icon: "fa-tower-broadcast", difficulty: "Intermediate" },
  { name: "Wifite", category: "Wireless", description: "Automated wireless attack tool.", usage: "wifite", icon: "fa-broom", difficulty: "Beginner" },
  { name: "Reaver", category: "Wireless", description: "WPS brute force attack tool.", usage: "reaver -i wlan0mon -b MAC", icon: "fa-key", difficulty: "Intermediate" },
  { name: "Bully", category: "Wireless", description: "Implementation of the WPS brute force attack.", usage: "bully wlan0mon -b MAC", icon: "fa-bullseye", difficulty: "Intermediate" },
  { name: "Fluxion", category: "Wireless", description: "Security auditing and research tool for wireless networks.", usage: "fluxion", icon: "fa-water", difficulty: "Intermediate" },
  { name: "Airgeddon", category: "Wireless", description: "Multi-use bash script for Linux systems to audit wireless networks.", usage: "airgeddon", icon: "fa-plane", difficulty: "Intermediate" },
  { name: "Bettercap", category: "Wireless", description: "The Swiss Army knife for network attacks and monitoring.", usage: "bettercap", icon: "fa-hat-wizard", difficulty: "Advanced" },
  { name: "EAPHammer", category: "Wireless", description: "Targeted rogue AP attacks and evil twin attacks.", usage: "eaphammer", icon: "fa-hammer", difficulty: "Advanced" },

  // --- REVERSE ENGINEERING ---
  { name: "Ghidra", category: "RE", description: "NSA's reverse engineering framework.", usage: "ghidra", icon: "fa-dna", difficulty: "Advanced" },
  { name: "IDA Pro", category: "RE", description: "Disassembler and debugger.", usage: "idapro", icon: "fa-code", difficulty: "Advanced" },
  { name: "Radare2", category: "RE", description: "Portable reverse engineering framework.", usage: "r2 binary", icon: "fa-terminal", difficulty: "Advanced" },
  { name: "Binary Ninja", category: "RE", description: "Reverse engineering platform.", usage: "binaryninja", icon: "fa-user-ninja", difficulty: "Advanced" },
  { name: "OllyDbg", category: "RE", description: "32-bit assembler level analyzing debugger.", usage: "ollydbg", icon: "fa-bug", difficulty: "Intermediate" },
  { name: "x64dbg", category: "RE", description: "Open-source x64/x32 debugger for Windows.", usage: "x64dbg", icon: "fa-bug", difficulty: "Intermediate" },
  { name: "JADX", category: "RE", description: "Dex to Java decompiler.", usage: "jadx-gui", icon: "fa-file-code", difficulty: "Beginner" },
  { name: "Bytecode Viewer", category: "RE", description: "Java 8 Jar & Android APK reverse engineering suite.", usage: "bytecode-viewer", icon: "fa-eye", difficulty: "Intermediate" },
  { name: "Frida", category: "RE", description: "Dynamic instrumentation toolkit.", usage: "frida -U -f com.app", icon: "fa-syringe", difficulty: "Advanced" },
  { name: "Hopper", category: "RE", description: "Reverse engineering tool for OS X and Linux.", usage: "hopper", icon: "fa-rabbit", difficulty: "Intermediate" },

  // --- SNIFFING & SPOOFING ---
  { name: "Wireshark", category: "Sniffing", description: "Network protocol analyzer.", usage: "wireshark", icon: "fa-fish", difficulty: "Beginner" },
  { name: "Tcpdump", category: "Sniffing", description: "Command-line packet analyzer.", usage: "tcpdump -i eth0", icon: "fa-terminal", difficulty: "Intermediate" },
  { name: "Ettercap", category: "Sniffing", description: "Comprehensive suite for man in the middle attacks.", usage: "ettercap -G", icon: "fa-plug", difficulty: "Intermediate" },
  { name: "Responder", category: "Sniffing", description: "LLMNR, NBT-NS and MDNS poisoner.", usage: "responder -I eth0", icon: "fa-reply", difficulty: "Intermediate" },
  { name: "Mitmproxy", category: "Sniffing", description: "An interactive TLS-capable intercepting HTTP proxy.", usage: "mitmproxy", icon: "fa-shield", difficulty: "Intermediate" },
  { name: "Evilginx2", category: "Sniffing", description: "Standalone man-in-the-middle attack framework.", usage: "evilginx2", icon: "fa-user-secret", difficulty: "Advanced" },
  { name: "Yersinia", category: "Sniffing", description: "Network tool designed to take advantage of weak network protocols.", usage: "yersinia -G", icon: "fa-biohazard", difficulty: "Advanced" },

  // --- FORENSICS ---
  { name: "Volatility", category: "Forensics", description: "Advanced memory forensics framework.", usage: "vol.py -f mem.raw", icon: "fa-microchip", difficulty: "Advanced" },
  { name: "Autopsy", category: "Forensics", description: "Digital forensics platform.", usage: "autopsy", icon: "fa-magnifying-glass-chart", difficulty: "Intermediate" },
  { name: "Sleuth Kit", category: "Forensics", description: "Collection of command line tools for disk analysis.", usage: "tsk_recover", icon: "fa-kit-medical", difficulty: "Intermediate" },
  { name: "Foremost", category: "Forensics", description: "Program to recover files based on their headers.", usage: "foremost -i image.dd", icon: "fa-file-medical", difficulty: "Beginner" },
  { name: "Binwalk", category: "Forensics", description: "Tool for searching binary images for embedded files.", usage: "binwalk image.bin", icon: "fa-shoe-prints", difficulty: "Intermediate" },
  { name: "ExifTool", category: "Forensics", description: "Read, write and edit meta information in files.", usage: "exiftool image.jpg", icon: "fa-camera", difficulty: "Beginner" },
  { name: "Bulk Extractor", category: "Forensics", description: "Extract features such as emails and URLs from disk images.", usage: "bulk_extractor image.dd", icon: "fa-filter", difficulty: "Intermediate" },

  // --- CLOUD SECURITY ---
  { name: "Pacu", category: "Cloud", description: "AWS exploitation framework.", usage: "python3 pacu.py", icon: "fa-cloud", difficulty: "Advanced" },
  { name: "Prowler", category: "Cloud", description: "AWS security best practices assessment.", usage: "prowler aws", icon: "fa-cloud-shield", difficulty: "Intermediate" },
  { name: "Scout Suite", category: "Cloud", description: "Multi-cloud security auditing tool.", usage: "scout aws", icon: "fa-binoculars", difficulty: "Intermediate" },
  { name: "Cloud_Enum", category: "Cloud", description: "OSINT tool for cloud assets.", usage: "cloud_enum -k target", icon: "fa-cloud-meatball", difficulty: "Beginner" },
  { name: "Peirates", category: "Cloud", description: "Kubernetes penetration tool.", usage: "peirates", icon: "fa-dharmachakra", difficulty: "Advanced" },
  { name: "Kube-hunter", category: "Cloud", description: "Hunt for security weaknesses in Kubernetes clusters.", usage: "kube-hunter", icon: "fa-cubes", difficulty: "Intermediate" },

  // --- MISC / UTILS ---
  { name: "CyberChef", category: "Utils", description: "The Swiss Army Knife of data conversion.", usage: "cyberchef", icon: "fa-bowl-food", difficulty: "Beginner" },
  { name: "Impacket", category: "Utils", description: "Collection of Python classes for working with network protocols.", usage: "psexec.py", icon: "fa-plug", difficulty: "Intermediate" },
  { name: "Chisel", category: "Utils", description: "Fast TCP/UDP tunnel over HTTP.", usage: "chisel server -p 8080", icon: "fa-tunnel", difficulty: "Intermediate" },
  { name: "Ngrok", category: "Utils", description: "Expose local servers to the internet.", usage: "ngrok http 80", icon: "fa-broadcast-tower", difficulty: "Beginner" },
  { name: "Zrok", category: "Utils", description: "Open source sharing platform (alternative to Ngrok).", usage: "zrok share reserved", icon: "fa-share-nodes", difficulty: "Beginner" },
  { name: "BloodHound", category: "Active Directory", description: "AD attack path visualization.", usage: "bloodhound", icon: "fa-skull", difficulty: "Advanced" },
  { name: "CrackMapExec", category: "Active Directory", description: "Swiss army knife for AD assessment.", usage: "cme smb target", icon: "fa-toolbox", difficulty: "Intermediate" },
  { name: "Rubeus", category: "Active Directory", description: "Toolset for raw Kerberos interaction.", usage: "rubeus triage", icon: "fa-shield-dog", difficulty: "Advanced" },
  { name: "Mimikatz", category: "Active Directory", description: "Extract passwords from memory.", usage: "mimikatz", icon: "fa-cat", difficulty: "Advanced" },
  { name: "SharpView", category: "Active Directory", description: "C# implementation of PowerView.", usage: "SharpView.exe Get-DomainUser", icon: "fa-eye", difficulty: "Intermediate" },
  { name: "PowerView", category: "Active Directory", description: "PowerShell tool for domain enumeration.", usage: "Get-NetUser", icon: "fa-powershell", difficulty: "Intermediate" },

  // --- ADDING MORE TO REACH 150+ ---
  { name: "Fuff", category: "Web Fuzzing", description: "Fast web fuzzer.", usage: "ffuf -u http://target/FUZZ -w wordlist.txt", icon: "fa-wind", difficulty: "Beginner" },
  { name: "Wfuzz", category: "Web Fuzzing", description: "The Web Fuzzer.", usage: "wfuzz -c -z file,wordlist.txt --hc 404 http://target/FUZZ", icon: "fa-vial", difficulty: "Intermediate" },
  { name: "Wpscan", category: "Web Scan", description: "WordPress vulnerability scanner.", usage: "wpscan --url url", icon: "fa-wordpress", difficulty: "Beginner" },
  { name: "SQLMap", category: "Databases", description: "SQL Injection.", usage: "sqlmap -u target", icon: "fa-database", difficulty: "Intermediate" },
  { name: "Nosqlmap", category: "Databases", description: "NoSQL Database exploitation.", usage: "nosqlmap", icon: "fa-database", difficulty: "Advanced" },
  { name: "Beef", category: "Web Hooks", description: "Browser Exploitation Framework.", usage: "beef-xss", icon: "fa-hook", difficulty: "Advanced" },
  { name: "Metasploit", category: "Exploitation", description: "Framework.", usage: "msfconsole", icon: "fa-rocket", difficulty: "Intermediate" },
  { name: "ExploitDB", category: "Archives", description: "The official archive of exploits.", usage: "searchsploit", icon: "fa-archive", difficulty: "Beginner" },
  { name: "PacketStorm", category: "Archives", description: "Security advisories and exploits.", usage: "packetstorm", icon: "fa-cloud-bolt", difficulty: "Beginner" },
  { name: "Snort", category: "IDS", description: "Intrusion Detection System.", usage: "snort -c snort.conf", icon: "fa-eye", difficulty: "Intermediate" },
  { name: "Suricata", category: "IDS", description: "Network threat detection engine.", usage: "suricata -c suricata.yaml", icon: "fa-eye-slash", difficulty: "Advanced" },
  { name: "Zeke", category: "Network Monitoring", description: "Network analysis framework.", usage: "zeekctl", icon: "fa-chart-line", difficulty: "Advanced" },
  { name: "SANS SIFT", category: "Forensics", description: "Forensics toolkit.", usage: "sift", icon: "fa-suitcase", difficulty: "Advanced" },
  { name: "Kali Linux", category: "OS", description: "Penetration Testing OS.", usage: "kali", icon: "fa-dragon", difficulty: "Beginner" },
  { name: "Parrot OS", category: "OS", description: "Security OS.", usage: "parrot", icon: "fa-dove", difficulty: "Beginner" },
  { name: "BlackArch", category: "OS", description: "Arch-based security OS.", usage: "blackarch", icon: "fa-ghost", difficulty: "Advanced" },
  { name: "Hak5 Pineapple", category: "Hardware", description: "WiFi auditing tool.", usage: "pineapple", icon: "fa-fruit-apple", difficulty: "Intermediate" },
  { name: "Rubber Ducky", category: "Hardware", description: "Keystroke injection tool.", usage: "ducky", icon: "fa-keyboard", difficulty: "Beginner" },
  { name: "Bash Bunny", category: "Hardware", description: "Multi-payload USB attack tool.", usage: "bunny", icon: "fa-rabbit", difficulty: "Intermediate" },
  { name: "Flipper Zero", category: "Hardware", description: "Multi-tool for geeks.", usage: "flipper", icon: "fa-gamepad", difficulty: "Intermediate" },
  { name: "Proxmark3", category: "Hardware", description: "RFID research tool.", usage: "proxmark3", icon: "fa-id-card", difficulty: "Advanced" },
  { name: "Ubertooth One", category: "Hardware", description: "Bluetooth monitoring tool.", usage: "ubertooth-scan", icon: "fa-bluetooth", difficulty: "Advanced" },
  { name: "Alfa AWUS036ACM", category: "Hardware", description: "WiFi adapter for monitor mode.", usage: "airmon-ng start wlan0", icon: "fa-wifi", difficulty: "Beginner" },
  { name: "O.MG Cable", category: "Hardware", description: "Malicious USB cable.", usage: "omg-cable", icon: "fa-plug", difficulty: "Advanced" },
  { name: "Spyder", category: "Hardware", description: "Hardware tool.", usage: "spyder", icon: "fa-microchip", difficulty: "Advanced" },
  { name: "HackRF One", category: "Hardware", description: "SDR transceiver.", usage: "hackrf_info", icon: "fa-tower-cell", difficulty: "Advanced" },
  { name: "LimeSDR", category: "Hardware", description: "Low cost SDR.", usage: "LimeUtil", icon: "fa-tower-observation", difficulty: "Advanced" },
  { name: "RTLSDR", category: "Hardware", description: "Low cost SDR receiver.", usage: "rtl_test", icon: "fa-radio", difficulty: "Beginner" },
  { name: "YARD Stick One", category: "Hardware", description: "Sub-GHz wireless transceiver.", usage: "yardstick", icon: "fa-ruler", difficulty: "Advanced" },
  { name: "PlutoSDR", category: "Hardware", description: "SDR for learning.", usage: "pluto", icon: "fa-planet-ring", difficulty: "Intermediate" },
  { name: "USRP", category: "Hardware", description: "Universal Software Radio Peripheral.", usage: "uhd_find_devices", icon: "fa-satellite-dish", difficulty: "Advanced" },
  { name: "NFC Kill", category: "Hardware", description: "NFC fuzzer/killer.", usage: "nfckill", icon: "fa-ban", difficulty: "Intermediate" },
  { name: "KeySweeper", category: "Hardware", description: "Stealthy wireless keyboard sniffer.", usage: "keysweeper", icon: "fa-keyboard", difficulty: "Advanced" },
  { name: "MagSpoof", category: "Hardware", description: "Magnetic stripe spoofer.", usage: "magspoof", icon: "fa-credit-card", difficulty: "Advanced" },
  { name: "OpenGarages", category: "Hardware", description: "Car hacking tool.", usage: "can-utils", icon: "fa-car", difficulty: "Advanced" },
  { name: "SavvyCAN", category: "Hardware", description: "CAN bus analyzer.", usage: "savvycan", icon: "fa-car-on", difficulty: "Intermediate" },
  { name: "Bus Pirate", category: "Hardware", description: "Universal bus interface.", usage: "buspirate", icon: "fa-microchip", difficulty: "Advanced" },
  { name: "JTAGulator", category: "Hardware", description: "Identify JTAG pinouts.", usage: "jtagulator", icon: "fa-bug", difficulty: "Advanced" },
  { name: "ChipWhisperer", category: "Hardware", description: "Side-channel power analysis tool.", usage: "chipwhisperer", icon: "fa-whiskey-glass", difficulty: "Advanced" },
];
